name: neut
version: 0.2.0.0
license: ISC
license-file: license.txt
author: "vekatze"
maintainer: "vekatze@icloud.com"

extra-source-files:
  - readme.org

default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - TupleSections
  - TypeFamilies

dependencies:
  - ansi-terminal
  - async
  - base
  - base64-bytestring
  - binary
  - bytestring
  - containers
  - cryptohash-sha256
  - exceptions
  - filepath
  - free
  - half
  - hashable
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - path
  - path-io
  - pqueue
  - process
  - safe-exceptions
  - template-haskell
  - text
  - time
  - unboxed-ref
  - unliftio-core
  - unordered-containers
  - utf8-string

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  neut:
    main: Main.hs
    source-dirs: main
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - neut

tests:
  neut-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neut
