name: neut
version: 0.3.0.0
license: ISC
license-file: license.md
author: "vekatze"
maintainer: "vekatze@icloud.com"

extra-source-files:
  - readme.org

language: GHC2021

default-extensions:
  - ApplicativeDo
  - OverloadedStrings
  - RecordWildCards
  - StrictData

dependencies:
  - ansi-terminal
  - async
  - base
  - base64-bytestring
  - binary
  - bytestring
  - containers
  - cryptohash-sha256
  - directory
  - exceptions
  - filepath
  - free
  - half
  - hashable
  - lsp
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - path
  - path-io
  - pqueue
  - process
  - safe-exceptions
  - template-haskell
  - text
  - time
  - unboxed-ref
  - unliftio
  - unliftio-core
  - unordered-containers
  - utf8-string
  - vector

executables:
  neut:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -j
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -fmax-pmcheck-models=100
