name: Tests on macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'bin/**'
      - 'book/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'bin/**'
      - 'book/**'

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ./llvm
          key: llvm-16.0.4
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0.4"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - uses: freckle/stack-action@v4
        with:
          pedantic: false
      - run: just build-compiler-amd64-darwin
      - run: just test-amd64-darwin
