name: Tests on macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'bin/**'
      - 'book/**'

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - run: brew update --preinstall
      - run: cp "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb" llvm.rb
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
            ~/Library/Caches/Homebrew/downloads
          key: brew-${{ hashFiles('llvm.rb') }}
      - run: brew install llvm
      - uses: freckle/stack-action@v4
      - run: just build-compiler-amd64-darwin
      - run: just test-amd64-darwin
