name: Tests on macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'bin/**'
      - 'book/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'bin/**'
      - 'book/**'

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - run: brew update --preinstall
      - run: cp "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb" llvm.rb
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew
            ~/Library/Caches/Homebrew/downloads
          key: brew-${{ hashFiles('llvm.rb') }}
      - run: |
          rm /usr/local/bin/2to3
          rm /usr/local/bin/2to3-3.11
          rm /usr/local/bin/idle3
          rm /usr/local/bin/idle3.11
          rm /usr/local/bin/pydoc3
          rm /usr/local/bin/pydoc3.11
          rm /usr/local/bin/python3
          rm /usr/local/bin/python3-config
          rm /usr/local/bin/python3.11
          rm /usr/local/bin/python3.11-config
      - run: brew install llvm@16
      - uses: freckle/stack-action@v4
        with:
          pedantic: false
      - run: just build-compiler-amd64-darwin
      - run: just test-amd64-darwin
